# Generated by Django 2.2.5 on 2020-10-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201031_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('other', 'Other'), ('female', 'Female'), ('male', 'Male')], max_length=10, null=True),
        ),
    ]
