# Generated by Django 2.2.5 on 2020-11-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20201102_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Room'),
        ),
    ]
